name = "Unnamed Modpack"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b6a07be0e7dd153731e01aec202dec0f0fb4c1f2a243a413159238c541a1f15"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
