name = "Unnamed Modpack"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "586d87182183db1a2e0f16c0ab4d3f1b67aa046935857ea5d68828ec0884efea"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
