name = "Unnamed Modpack"
author = "Lutfilah Dzaky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "597beca88ae4551c1df441cf4d7c7b9892c9981872228e9c3f2624e827e8d10e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
