[server]
	containerItemsDisallowed = true
	[server.leatherBackpack]
		inventorySlotCount = 9
	[server.copperBackpack]
		inventorySlotCount = 18
	[server.ironBackpack]
		inventorySlotCount = 27
	[server.goldBackpack]
		inventorySlotCount = 36
	[server.diamondBackpack]
		inventorySlotCount = 57
	[server.netheriteBackpack]
		inventorySlotCount = 85
	[server.nerfs]
		tooManyBackpacksSlowness = true
		maxNumberOfBackpacks = 2
		slownessLevelsPerAdditionalBackpack = 2.0
